services:
  blackbulb:
    build:
      context: ./blackbulb
      dockerfile: Dockerfile
    image: blackbulb
    container_name: blackbulb
    restart: always
    environment:
      - BLACKBULB_BOT_TOKEN
  lightbulb:
    build:
      context: ./lightbulb
      dockerfile: Dockerfile
    image: lightbulb
    container_name: lightbulb
    restart: always
    environment:
      - LIGHTBULB_BOT_TOKEN
